FriendsApp/Models/ErrorViewModel.cs
namespace FriendsApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FriendsApp/Models/Friend.cs
namespace FriendsApp.Models
{
    public class Friend
    {
        public string Name { get; set; }
        public int Number { get; set; }
        public string Image { get; set; }
    }
   
}

FriendsApp/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Mvc;
using FriendsApp.Models; 

namespace FriendsApp.Controllers
{
    public class FriendsController : Controller
    {
        public static List<Friend> friends = new List<Friend>(); 
        public IActionResult List()
        {
            return View(friends);
        }
        static FriendsController()
        {
            friends.Add(new Friend
            {
                Number = 1,
                Name = "Ali",
                Image  = ".././Img/p1.png"
            });
            friends.Add(new Friend
            {
                Number = 2,
                Name = "Ana",
                Image = ".././Img/p2.png"
            });
            friends.Add(new Friend
            {
                Number = 3,
                Name = "Baran",
                Image = ".././Img/p3.png"
            });
            friends.Add(new Friend
            {
                Number = 4,
                Name = "Bahram",
                Image = ".././Img/p4.png"
            });
            friends.Add(new Friend
            {
                Number = 5,
                Name = "Sara",
                Image = ".././Img/p5.png"
            });
            friends.Add(new Friend
            {
                Number = 6,
                Name = "Sina",
                Image = ".././Img/p6.png"
            });
            friends.Add(new Friend
            {
                Number = 7,
                Name = "Saba",
                Image = ".././Img/p7.png"
            });
            friends.Add(new Friend
            {
                Number = 8,
                Name = "Anne",
                Image = ".././Img/p8.png"
            });
            friends.Add(new Friend
            {
                Number = 9,
                Name = "Radin",
                Image = ".././Img/p9.png"
            });
            friends.Add(new Friend
            {
                Number = 10,
                Name = "Mina",
                Image = ".././Img/p10.png"
            });
        }
        public IActionResult Detail(int id)
        {
            var friend = friends.FirstOrDefault(f => f.Number == id);
            if (friend == null)
            {
                return NotFound();
            }
            return View(friend);
        }

 
        [HttpGet]
        public IActionResult NewPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewPage(Friend friend)
        {
            friends.Add(friend);
            return RedirectToAction("List");
        }

    }
}

FriendsApp/Controllers/HomeController.cs
using FriendsApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FriendsApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FriendsApp/Views/Friends/Detail.cshtml
@model Friend 
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <h3 class="text-center py-4">Friend Number @Model.Number </h3>

    <!--test 2 -->
    <div class="row d-flex justify-content-center">
        <div class="text-center py-3 border border-info-subtle rounded-3 col-md-6">
            <img class="rounded-circle" src="../@Model.Image" alt="Friend image" />
            <h2 class="fw-bold text-dark mt-2">@Model.Name</h2>
            <p class="text-secondary">The Number of my friend is: <span class="text-primary">@Model.Number</span></p>
            <p> <a class="btn btn-secondary" asp-controller="Friends" asp-action="List">View another friends »</a> </p>
            
        </div>
    </div>
</div>

FriendsApp/Views/Friends/List.cshtml
@model List<Friend>
@* @model Friend11 *@
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container text-center">
    <h1> My Friends List</h1>
    <p>This List show the Top 10 of My friends: </p>

    <table class="table">
        <thead class="table-primary">
            <tr class="text-center">
                <th class="">Number</th>
                <th class="">MyFriendsName</th>
                <th class="">Image</th>
            </tr>
        </thead>
        <tbody >
             @foreach(var item in Model)
             {
                <tr class="align-items-center">
                    <td class="">@item.Number</td>
                    <td class="">@item.Name</td>
                    <td class="img-fluid"><img src="@item.Image" alt="Friend image" /></td>
                </tr>
             }
        </tbody>
    </table>

    <div class="row d-flex justify-content-center">
        <div class="text-center py-3 border border-info bg-light rounded-3 col-md-6">
            <p class="text-dark">Can't Find your best friend's name? </p>
            <p> <a class="btn btn-info" asp-controller="Friends" asp-action="NewPage"> Click Here » </a> </p>
        </div>
    </div>
</div>

FriendsApp/Views/Friends/NewPage.cshtml
@model Friend
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <h3 class="text-center py-4"> Add a New Friend </h3>

    <!--test 2 -->
    <div class="row d-flex justify-content-center">
        <div class="text-center py-3 border border-info-subtle rounded-3 col-md-6">

            <form method="post" asp-controller="Friends" asp-action="NewPage">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label">Name: </label>
                    <input asp-for="Name" class="form-control">
                </div>

                <div class="mb-3">
                    <label asp-for="Number" class="form-label">Number: </label>
                    <input asp-for="Number" class="form-control">
                </div>

                <div class="mb-3">
                    <label asp-for="Image" class="form-label">Image Url: </label>
                    <input asp-for="Image" class="form-control">
                </div>

                <button type="submit" class="btn btn-secondary">Submit</button>
            </form>

        </div>
    </div>
</div>

FriendsApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center container py-5">
            <h1 class="display-4 pb-5">Welcome</h1>
            <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
            <p class="py-3">you can see your <a class="text-success" asp-controller="Friends" asp-action="List">friends List </a> </p>
            <p class="py-3">Or add a <a class="text-danger" asp-controller="Friends" asp-action="NewPage">New friend  </a> </p>
</div>

FriendsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FriendsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FriendsApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FriendsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FriendsApp/Views/Shared/_footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<footer class="border-top footer text-muted">
    <div class="container">
        <p> &copy; July 2023 </p>
        <p> FriendsApp.com - <a asp-controller="Friends" asp-action="List">Friends List</a></p>
    </div>
</footer>